### ISSUE TITLE
Consider using lowercase function names for the plots

### ISSUE THREAD

**Issue by juliohm** [SeismicJulia/SeisMakie.jl#13]
The plots are usually defined as lowercase functions. Uppercase is used for types.

I would also try to follow a convention where you end the recipes with a `plot` suffix, something like:

```julia
fig, ax = seisplot(d, style = ..., kind = ...)
```

**Comment by AtilaSaraiva** [comment]
Hello @juliohm , thanks for the input. I agree with your suggestions, although the reason we sticked with the current notation is to maintain feature parity with SeisPlot.jl, but you are right. I'm going to arange for this new style to be adopted and link the PR here.

**Comment by juliohm** [comment]
Also, seismic data (especially post-stack) could be loaded and visualized with the geospatial data science stack we are building at https://juliaearth.github.io/geospatial-data-science-with-julia

Perhaps we could increase synergy between ecosystems by following this established interface.
